### ISSUE TITLE
Registrar Pago Personal [5]

### ISSUE THREAD

**Issue by MegaRedHand** [VaquitApp/backend#52]
**Descripción**
Permitir a un usuario ingresar un registro de pago a otro usuario, con monto y recipiente.

**Tareas**
Listado de tareas que componen a la historia.

- [x] Nuevo POST para registrar pagos personales
- [x] Nuevo GET para listar pagos personales

**Comment by mrti259** [comment]
deberia estar cerrado esto no?

**Comment by MegaRedHand** [comment]
Sí
